---
title: "Probability Theory"
author: "Rithika Rao Dodda"
number-sections: false
---
# Assignment 1

```{r}
# Probability of change in scope S
S<-0.3

# Probability (T | S)
T_S<-0.2

# Probability (T | ¬S)
T_NOT_S<-0.6


# Calculate the remaining values based upon the 3 variables above
NOT_T_S<-1-T_S
NOT_S<-1-S
NOT_T_NOT_S<-1-T_NOT_S

#Joint Probabilities of S and T, S and notT, notS and T, notS and notT
S_AND_T<-S*T_S
S_AND_NOT_T<-S*NOT_T_S
NOT_S_AND_T <- NOT_S*T_NOT_S
NOT_S_AND_NOT_T <- NOT_S*NOT_T_NOT_S

# Sum of probabilities
sum_of_probabilites <- S_AND_T + S_AND_NOT_T + NOT_S_AND_T + NOT_S_AND_NOT_T

# Displaying the results
cat("P(T ∩ S):", S_AND_T, "\n")
cat("P(T ∩ S'): ", NOT_S_AND_T , "\n")
cat("P(T' ∩ S):", S_AND_NOT_T , "\n")
cat("P(T' ∩ S'): ", NOT_S_AND_NOT_T, "\n")
cat("Sum of probabilities:", sum_of_probabilites, "\n")

```

# Assignment 2
```{r}
# Given probabilities
P_A <- 0.423
P_B <- 0.278
P_C <- 0.1
P_A_intersect_B <- 0.073
P_B_intersect_C <- 0.033
P_A_intersect_C <- 0.088
P_A_intersect_B_intersect_C <- 0.005

# Calculate the percentage of customers using all three devices
P_all_three <- P_A_intersect_B_intersect_C * 100

# Calculate the percentage of customers using at least two devices
P_at_least_two <- (P_A + P_B + P_C - P_A_intersect_B - P_B_intersect_C - P_A_intersect_C +
                   P_A_intersect_B_intersect_C) * 100

# Calculate the percentage of customers using only one device
P_only_one <- ((P_A - P_A_intersect_B - P_A_intersect_C + P_A_intersect_B_intersect_C) +
               (P_B - P_A_intersect_B - P_B_intersect_C + P_A_intersect_B_intersect_C) +
               (P_C - P_A_intersect_C - P_B_intersect_C + P_A_intersect_B_intersect_C)) * 100

# Print results
cat("Percentage of customers using all three devices:", P_all_three, "\n")
cat("Percentage of customers using at least two devices:", P_at_least_two, "\n")
cat("Percentage of customers using only one device:", P_only_one, "\n")

```

# Assignment 3
```{r}
# Given probabilities
P_B_A <- 0.97
P_B_notA <- 0.01
P_A <- 0.04
not_P_A <- 1 - P_A

# Calculate the probability B
P_B <- P_B_A * P_A + P_B_notA * not_P_A
cat("Probability of B:", P_B, "\n")
# Calculate the probability A|B using conditional probability formula
P_A_B <- P_B_A * P_A / P_B
cat("Probability of P_A_B:", P_A_B, "\n")
# Calculate the probability not_A|B using conditional probability formula
P_not_A_B <- P_B_notA * not_P_A / P_B
cat("Probability of P_not_A_B:", P_not_A_B, "\n")
```
The following sentence: 
These results show that in case the alarm is triggered, there is a possibility of about 19.83% that the product is flawless and a probability of 80.16% that the product is faulty.




